
# Gender definitions
uint8 MALE=0
uint8 FEMALE=1

# Gender, either MALE of FEMALE
uint8 gender

# The age of the face
uint8 age

# Glasses, either 0 for FALSE or 1 for TRUE
uint8 glasses

# Sunglasses, either 0 for FALSE or 1 for TRUE
uint8 sunglasses

# Eyes, String
string eyes

# Lips, String
string lips

# Smiling, either 0 for FALSE or 1 for TRUE
uint8 smiling

# Mood, String
string mood

# Neutral, either 0 for FALSE or 1 for TRUE
uint8 neutral

# Anger, either 0 for FALSE or 1 for TRUE
uint8 anger

# Disgust, either 0 for FALSE or 1 for TRUE
uint8 disgust

# Fear, either 0 for FALSE or 1 for TRUE
uint8 fear

# Happiness, either 0 for FALSE or 1 for TRUE
uint8 happiness

# Sadness, either 0 for FALSE or 1 for TRUE
uint8 sadness

# Surprise, either 0 for FALSE or 1 for TRUE
uint8 surprise


